# Generated by Django 4.0.2 on 2022-02-26 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='creator',
            field=models.IntegerField(default=0),
        ),
    ]
