# Generated by Django 4.0.2 on 2022-02-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDoApp', '0002_alter_tasklist_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='creator',
            field=models.IntegerField(default=0),
        ),
    ]
